import streamlit as st
import pandas as pd
import numpy as np
import torch
import google.generativeai as genai
import json
import plotly.express as px
import plotly.graph_objects as go
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import io
import os


def generate_html_report(df_info, goal, target, plan, logs, metrics):
    """Generates a simple HTML report summary."""
    html = f"""
    <html>
    <head>
        <title>Data Preprocessing Report</title>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }}
            h1 {{ color: #2c3e50; }}
            h2 {{ color: #34495e; margin-top: 30px; }}
            .card {{ background: #f8f9fa; border-left: 5px solid #3498db; padding: 15px; margin-bottom: 20px; }}
            table {{ border-collapse: collapse; width: 100%; margin-top: 10px; }}
            th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
            th {{ background-color: #f2f2f2; }}
        </style>
    </head>
    <body>
        <h1>📊 AI Data Preprocessing Report</h1>
        <p>Generated by Tensorifier Agent</p>
        
        <div class="card">
            <h2>1. Project Overview</h2>
            <ul>
                <li><strong>Goal:</strong> {goal}</li>
                <li><strong>Target Variable:</strong> {target}</li>
                <li><strong>Final Data Shape:</strong> {df_info}</li>
            </ul>
        </div>

        <div class="card">
            <h2>2. Execution Metrics</h2>
            <p>{metrics}</p>
        </div>

        <h2>3. Applied Preprocessing Steps</h2>
        <table>
            <tr><th>Column</th><th>Action</th><th>Reason</th></tr>
    """
    for item in plan:
        html += f"<tr><td>{item['col']}</td><td>{item['action']}</td><td>{item.get('reason', '-')}</td></tr>"
    
    html += """
        </table>

        <h2>4. Execution Log</h2>
        <ul>
    """
    for log in logs:
        html += f"<li>{log}</li>"
    
    html += """
        </ul>
    </body>
    </html>
    """
    return html

def generate_python_code(plan, target_col):
    """전처리 과정을 파이썬 코드로 변환합니다."""
    code = f"""import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
import torch

# 1. Load Data
# df = pd.read_csv('your_data_file.csv') # Replace with your file path

# 2. Preprocessing Steps
"""
    for item in plan:
        col = item['col']
        action = item['action']
        if action == "Pass": continue
        
        code += f"\n# [{col}] - {action}\n"
        code += f"if '{col}' in df.columns:\n"
        
        if action == "Drop":
            code += f"    df = df.drop(columns=['{col}'])\n"
        elif action == "Fill_Median":
            code += f"    if pd.api.types.is_numeric_dtype(df['{col}']):\n"
            code += f"        val = df['{col}'].median()\n"
            code += f"        df['{col}'] = df['{col}'].fillna(val)\n"
        elif action == "Fill_Mode":
            code += f"    val = df['{col}'].mode()[0]\n"
            code += f"    df['{col}'] = df['{col}'].fillna(val)\n"
        elif action == "Fill_Zero":
            code += f"    df['{col}'] = df['{col}'].fillna(0)\n"
        elif action == "Normalize":
            code += f"    scaler = StandardScaler()\n"
            code += f"    df['{col}'] = scaler.fit_transform(df[['{col}']].values).flatten()\n"
        elif action == "Encode_Label":
            code += f"    le = LabelEncoder()\n"
            code += f"    df['{col}'] = df['{col}'].fillna('Unknown').astype(str)\n"
            code += f"    df['{col}'] = le.fit_transform(df['{col}'])\n"
        elif action == "Encode_OneHot":
            code += f"    dummies = pd.get_dummies(df['{col}'], prefix='{col}', drop_first=False)\n"
            code += f"    df = pd.concat([df.drop(columns=['{col}']), dummies], axis=1)\n"

    code += f"""
# 3. Target Separation & Tensor Creation
target_col = '{target_col}'
if target_col in df.columns:
    y = df[target_col].values
    X = df.drop(columns=[target_col])
else:
    # Handle One-Hot case
    target_cols = [c for c in df.columns if str(c).startswith(f"{{target_col}}_")]
    if target_cols:
        y = df[target_cols].values
        X = df.drop(columns=target_cols)
    else:
        print("Target column not found. Using all columns as X.")
        X = df
        y = np.zeros(len(df))

# Feature Type Cleaning
X = X.apply(pd.to_numeric, errors='coerce').fillna(0)
X_values = X.values.astype(np.float32)

# y handling
try:
    y = pd.to_numeric(y, errors='coerce')
    y = np.nan_to_num(y)
except:
    pass
y_values = np.array(y).astype(np.float32)

# Split
X_train, X_test, y_train, y_test = train_test_split(X_values, y_values, test_size=0.2, random_state=42)

# Convert to PyTorch Tensors
device = "cuda" if torch.cuda.is_available() else "cpu"
X_train_t = torch.tensor(X_train).to(device)
y_train_t = torch.tensor(y_train).to(device)

print(f"Propocessing Complete. X_train shape: {{X_train_t.shape}}")
"""
def generate_dask_code(plan, target_col):
    """Generates Dask code for Big Data processing (Lazy Evaluation)."""
    code = f"""import dask.dataframe as dd
import dask.array as da
import numpy as np

# 1. Load Data (Lazy Loading for Big Data > 100GB)
# ddf = dd.read_csv('your_big_data_*.csv') 
# client = Client() # Connect to cluster if needed

# 2. Preprocessing Steps
"""
    for item in plan:
        col = item['col']
        action = item['action']
        if action == "Pass": continue
        
        code += f"\n# [{col}] - {action}\n"
        # Dask uses lazy columns presence check usually, but for script generation we assume schema allows it.
        # We wrap in check logic if needed, but schema is usually fixed.
        code += f"# Action: {action}\n"
        
        if action == "Drop":
            code += f"if '{col}' in ddf.columns: ddf = ddf.drop(columns=['{col}'])\n"
        elif action == "Fill_Median":
            code += f"if '{col}' in ddf.columns:\n"
            code += f"    median_val = ddf['{col}'].median().compute() # Computes immediately\n"
            code += f"    ddf['{col}'] = ddf['{col}'].fillna(median_val)\n"
        elif action == "Fill_Mode":
            code += f"if '{col}' in ddf.columns:\n"
            code += f"    mode_val = ddf['{col}'].mode().compute().iloc[0]\n"
            code += f"    ddf['{col}'] = ddf['{col}'].fillna(mode_val)\n"
        elif action == "Fill_Zero":
             code += f"if '{col}' in ddf.columns: ddf['{col}'] = ddf['{col}'].fillna(0)\n"
        elif action == "Normalize":
            code += f"if '{col}' in ddf.columns:\n"
            code += f"    mean = ddf['{col}'].mean().compute()\n"
            code += f"    std = ddf['{col}'].std().compute()\n"
            code += f"    ddf['{col}'] = (ddf['{col}'] - mean) / std\n"
        elif action == "Encode_Label":
            code += f"if '{col}' in ddf.columns:\n"
            code += f"    ddf['{col}'] = ddf['{col}'].astype('category').cat.as_known().cat.codes\n"
        elif action == "Encode_OneHot":
            code += f"if '{col}' in ddf.columns:\n"
            code += f"    ddf = dd.get_dummies(ddf, columns=['{col}'])\n"

    code += f"""
# 3. Target & Output
target_col = '{target_col}'
# Dask operations are lazy. Trigger computation or save to parquet.
print("Saving processed data to Parquet (Distributed Write)...")
# ddf.to_parquet('processed_output.parquet')
print("Done.")
"""
    return code


# --- [1. 환경 설정 및 API 연결] ---
# ... (rest of the file)


# --- [1. 환경 설정 및 API 연결] ---
st.set_page_config(page_title="Data Preprocessing Agent", layout="wide")

GEMINI_API_KEY = None

# .streamlit/secrets.toml 파일이 존재하는지 먼저 확인 (에러 박스 방지)
secrets_exist = False
try:
    if os.path.exists(".streamlit/secrets.toml"):
        secrets_exist = True
    elif os.path.exists(os.path.join(os.path.expanduser("~"), ".streamlit", "secrets.toml")):
        secrets_exist = True
except:
    pass

if secrets_exist:
    try:
        if "GEMINI_API_KEY" in st.secrets:
            GEMINI_API_KEY = st.secrets["GEMINI_API_KEY"]
    except:
        pass

if not GEMINI_API_KEY:
    # secrets가 없으면 사용자에게 입력을 받거나 에러를 띄웁니다 (보안상 안전)
    GEMINI_API_KEY = st.text_input("Gemini API Key를 입력하세요:", type="password")
    if not GEMINI_API_KEY:
        st.warning("API Key가 설정되지 않았습니다. 로컬 실행 시 .streamlit/secrets.toml 파일을 확인하세요.")
        st.stop()

genai.configure(api_key=GEMINI_API_KEY)
# model = genai.GenerativeModel('gemini-pro') 
model = genai.GenerativeModel('gemini-2.5-flash') # Or gemini-1.5-pro-latest


# Toss 스타일 커스텀 CSS (단계별 진행 바 등 추가)
st.markdown("""
    <style>
    .main { background-color: #F9FAFB; }
    .stButton>button { width: 100%; border-radius: 12px; height: 3em; background-color: #0047FF; color: white; font-weight: bold; border: none; }
    .stProgress > div > div > div > div { background-color: #0047FF; }
    div[data-testid="stExpander"] { background-color: white; border-radius: 10px; border: 1px solid #E5E7EB; }
    </style>
""", unsafe_allow_html=True)

# --- [2. 도구 함수들] ---
def reset_state():
    """앱 상태를 초기화합니다."""
    st.session_state.clear()
    st.session_state.step = 'upload'
    st.session_state.current_step_idx = 0
    st.session_state.log = []

def suggest_goals(df):
    """데이터를 분석하여 적절한 분석 목표 4가지를 제안합니다."""
    cols = list(df.columns)
    sample = df.head(3).to_csv(index=False)
    
    prompt = f"""
    Analyze the dataset to propose 4 distinct and meaningful data analysis or machine learning goals.
    Columns: {cols}
    Data Sample: {sample}
    
    Return a valid JSON list of strings (Korean). Each string should be a short, actionable goal title.
    Example output: ["고객 이탈 예측 (Classification)", "매출 요인 분석 (Regression)", "사용자 패턴 세분화 (Clustering)", "이상 거래 탐지 (Anomaly Detection)"]
    
    Ensure the goals are tailored to the specific context of the data (e.g., if it's Titanic data, mention 'Survival Prediction').
    """
    try:
        response = model.generate_content(prompt)
        text = response.text.replace('```json', '').replace('```', '').strip()
        goals = json.loads(text)
        return goals if isinstance(goals, list) else []
    except Exception as e:
        print(f"Goal suggestion error: {e}")
        return ["데이터 탐색 (EDA)", "타겟 변수 예측", "데이터 클러스터링", "상관관계 분석"]

def suggest_target_column(df, goal=""):
    """데이터와 목표를 보고 타겟 컬럼을 추측합니다."""
    # 비용 절약을 위해 일부만 전송
    cols = list(df.columns)
    sample = df.head(3).to_csv(index=False)
    
    prompt = f"""
    Analyze the dataset columns and user goal to identify the most likely Target Column (Label) for Machine Learning.
    Columns: {cols}
    User Goal: {goal}
    Data Sample: {sample}
    
    Return ONLY the exact column name of the most likely target. If unsure, return the last column name.
    Do not add any explanation or quotes.
    """
    try:
        response = model.generate_content(prompt)
        suggested_col = response.text.strip().strip("'").strip('"')
        if suggested_col in df.columns:
            return suggested_col
        else:
            return df.columns[-1]
    except:
        return df.columns[-1]

def get_agent_plan(df, goal, target_col, mode="ML"):
    """Gemini가 전체 전처리 계획을 수립합니다 (모드별 차별화)."""
    sample_data = df.head(5).to_csv(index=False)
    null_info = df.isnull().mean().to_dict()
    column_types = df.dtypes.astype(str).to_dict()
    unique_counts = df.nunique().to_dict()
    
    # 모드별 프롬프트 분기
    if "머신러닝" in mode:
        role_desc = "Machine Learning Data Engineer"
        focus = "Prepare data for Model Training (One-Hot, Scaling, Imputation)."
        rule_cat = "Categorical columns MUST be encoded (OneHot or Label)."
        rule_target = f"Target '{target_col}' should be Label Encoded if categorical, or passed if numeric."
    else:
        role_desc = "Data Analyst (EDA Expert)"
        focus = "Clean data for Business Insight & Visualization."
        rule_cat = "Categorical columns can be kept as is or simplifed (e.g. Fillna). Encoding is optional."
        rule_target = f"Target '{target_col}' is the key metric. Ensure it is clean."

    prompt = f"""
    You are a {role_desc}.
    Goal: {goal}
    Target: {target_col}
    Mode: {mode} ({focus})
    
    Data Context:
    - Sample: {sample_data}
    - Null Ratios: {null_info}
    - Types: {column_types}
    - Unique Counts: {unique_counts}
    
    Task: Propose a step-by-step plan for each column.
    Available Actions: [Drop, Fill_Median, Fill_Mode, Fill_Zero, Normalize, Encode_OneHot, Encode_Label, Pass]
    
    Rules ({mode}):
    1. {rule_cat}
    2. {rule_target}
    3. Return a valid JSON list.
    
    [
        {{"col": "column_name", "action": "Selected Action", "reason": "Reason (Korean)"}}
    ]
    """
    try:
        response = model.generate_content(prompt)
        text = response.text.replace('```json', '').replace('```', '').strip()
        return json.loads(text)
    except Exception as e:
        print(f"Error calling Gemini: {e}") 
        return [{"col": c, "action": "Pass", "reason": f"API 오류로 기본 Pass 처리 ({str(e)})"} for c in df.columns]

def apply_step(df, col, action):
    """단일 스텝(컬럼 액션)을 수행하고 결과 데이터프레임을 반환합니다."""
    new_df = df.copy()
    
    if col not in new_df.columns:
        return new_df

    try:
        if action == "Drop":
            new_df = new_df.drop(columns=[col])
        elif action == "Fill_Median":
            if pd.api.types.is_numeric_dtype(new_df[col]):
                val = new_df[col].median()
                new_df[col] = new_df[col].fillna(val)
        elif action == "Fill_Mode":
            val = new_df[col].mode()[0]
            new_df[col] = new_df[col].fillna(val)
        elif action == "Fill_Zero":
            new_df[col] = new_df[col].fillna(0)
        elif action == "Normalize":
            if pd.api.types.is_numeric_dtype(new_df[col]):
                scaler = StandardScaler()
                data = new_df[[col]].values
                new_df[col] = scaler.fit_transform(data).flatten()
        elif action == "Encode_Label":
            le = LabelEncoder()
            # 결측치는 임시 처리 후 인코딩
            new_df[col] = new_df[col].fillna("Unknown").astype(str)
            new_df[col] = le.fit_transform(new_df[col])
        elif action == "Encode_OneHot":
            # One-Hot은 컬럼이 늘어나므로 처리가 조금 다릅니다.
            # 하지만 여기서는 해당 컬럼을 원핫 인코딩한 데이터프레임으로 교체합니다.
            dummies = pd.get_dummies(new_df[col], prefix=col, drop_first=False)
            new_df = pd.concat([new_df.drop(columns=[col]), dummies], axis=1)
            
    except Exception as e:
        st.error(f"Action '{action}' failed on '{col}': {e}")
            
    return new_df

def plot_comparison(old_df, new_df, col):
    """변경 전후 분포 비교 시각화 (Plotly)"""
    # 1. 컬럼이 사라진 경우 (Drop, OneHot 등)
    if col not in new_df.columns:
        st.info(f"ℹ️ '{col}' 컬럼은 처리 후 구조가 변경되었거나 삭제되었습니다. (예: One-Hot Encoding)")
        return

    col_c1, col_c2 = st.columns(2)
    
    # 2. 수치형 데이터 시각화
    if pd.api.types.is_numeric_dtype(new_df[col]):
        with col_c1:
            # Histogram
            fig = go.Figure()
            # Original
            fig.add_trace(go.Histogram(x=old_df[col].dropna(), name='Original', opacity=0.5, marker_color='gray'))
            # Transformed
            fig.add_trace(go.Histogram(x=new_df[col], name='Transformed', opacity=0.5, marker_color='blue'))
            fig.update_layout(title_text=f"{col} Distribution (Histogram)", barmode='overlay')
            st.plotly_chart(fig, use_container_width=True)
            
        with col_c2:
            # Box Plot
            fig2 = go.Figure()
            fig2.add_trace(go.Box(y=old_df[col].dropna(), name='Original', marker_color='gray'))
            fig2.add_trace(go.Box(y=new_df[col], name='Transformed', marker_color='blue'))
            fig2.update_layout(title_text=f"{col} Box Plot (Outliers)")
            st.plotly_chart(fig2, use_container_width=True)

        st.markdown("#### 🔢 통계 요약")
        desc_old = old_df[col].describe()
        desc_new = new_df[col].describe()
        stats_df = pd.DataFrame({'Original': desc_old, 'Transformed': desc_new})
        st.dataframe(stats_df.T, use_container_width=True)

    # 3. 범주형 데이터 시각화
    else:
        # 상위 10개 카테고리
        top_n = 10
        old_counts = old_df[col].value_counts().head(top_n)
        new_counts = new_df[col].value_counts().head(top_n)
        
        with col_c1:
            fig = px.bar(x=old_counts.index, y=old_counts.values, title=f"Original Top {top_n}", labels={'x':'Category', 'y':'Count'})
            st.plotly_chart(fig, use_container_width=True)
            
        with col_c2:
            fig2 = px.bar(x=new_counts.index, y=new_counts.values, title=f"Transformed Top {top_n}", labels={'x':'Category', 'y':'Count'})
            st.plotly_chart(fig2, use_container_width=True)

# --- [3. 메인 로직] ---
if 'step' not in st.session_state:
    st.session_state.step = 'upload'
    st.session_state.current_step_idx = 0
    st.session_state.log = [] 

# --- [Image Mode Logic] ---
def run_image_mode():
    st.header("🖼️ 이미지 데이터 전처리 (Image Preprocessing)")
    
    with st.expander("ℹ️ 사용 가이드", expanded=True):
        st.write("""
        1. **이미지 업로드**: 처리를 원하는 이미지들을 한꺼번에 업로드하세요.
        2. **옵션 설정**: 리사이즈 크기, 흑백 변환, 정규화 여부를 선택하세요.
        3. **변환 및 다운로드**: PyTorch Tensor `(N, C, H, W)` 형태로 변환하여 `.pt` 파일로 다운로드합니다.
        """)
        
    uploaded_files = st.file_uploader("이미지 파일 업로드 (JPG, PNG, WEBP)", type=['jpg', 'jpeg', 'png', 'webp'], accept_multiple_files=True)
    
    if uploaded_files:
        st.markdown("### ⚙️ 전처리 옵션")
        c1, c2, c3 = st.columns(3)
        target_size = c1.number_input("Resize Size (Square)", min_value=32, value=224, step=32)
        grayscale = c2.checkbox("Grayscale 변환", value=False)
        normalize = c3.checkbox("Normalize (0~1 Scaling)", value=True)
        
        st.markdown("---")
        st.subheader("👀 미리보기 (First 5 Images)")
        
        from PIL import Image
        import torchvision.transforms as T
        
        # Define Transform
        transforms_list = []
        transforms_list.append(T.Resize((target_size, target_size)))
        if grayscale:
            transforms_list.append(T.Grayscale(num_output_channels=1))
        transforms_list.append(T.ToTensor())
        # Note: ToTensor converts [0, 255] -> [0.0, 1.0] implicitly.
        # If user wants 0~1 scaling, ToTensor does it.
        # If user DOES NOT want it (wants 0-255), we might need to multiply by 255? 
        # Usually Tensor is float 0-1. Let's stick to standard ToTensor.
        
        transform = T.Compose(transforms_list)
        
        preview_cols = st.columns(5)
        processed_tensors = []
        
        for i, file in enumerate(uploaded_files):
            try:
                img = Image.open(file).convert('RGB')
                
                # Preview Original
                if i < 5:
                    with preview_cols[i]:
                        st.image(img, caption=f"Original {i+1}", use_container_width=True)
                
                # Process
                tensor = transform(img) # [C, H, W]
                processed_tensors.append(tensor)
                
            except Exception as e:
                st.error(f"{file.name} 처리 중 에러: {e}")

        if processed_tensors:
            # Stack: [N, C, H, W]
            batch_tensor = torch.stack(processed_tensors)
            
            st.success(f"✅ 총 {len(batch_tensor)}장 변환 완료! Shape: {batch_tensor.shape}")
            
            # Save
            buffer = io.BytesIO()
            torch.save(batch_tensor, buffer)
            st.download_button("💾 Download images.pt", buffer.getvalue(), "images.pt")

# --- [Main Layout Control] ---

# Sidebar Control
with st.sidebar:
    st.title("🎛️ Mode Selection")
    mode = st.selectbox("Data Type", ["Tabular Data (CSV/Excel)", "Image Data (JPG/PNG)"])
    
    st.markdown("---")
    
    # [Image Mode Entry Point]
    if mode == "Image Data (JPG/PNG)":
        run_image_mode()
        st.stop() # Stop further execution for Tabular mode

    # [Tabular Mode Continued...]
    st.header("🔧 Tabular Controls")
    
    # 1. Reset Button (Always accessible)
    if st.button("🔄 Start Over (Reset)", type="primary", use_container_width=True):
        reset_state()
        st.rerun()
    
    st.markdown("---")
    
    # 2. Progress Tracker
    steps = ["upload", "plan_edit", "execute_loop", "final"]
    step_labels = ["1. Upload & Goal", "2. Plan Review", "3. Processing", "4. Download"]
    
    current_idx = 0
    if st.session_state.step in steps:
        current_idx = steps.index(st.session_state.step)
    
    st.caption("� Current Progress")
    # Custom progress visualization using radio (disabled) to act as a stepper
    st.radio(
        "Steps", 
        step_labels, 
        index=current_idx, 
        disabled=True,
        label_visibility="collapsed"
    )
    
    st.markdown("---")
    
    # 3. Data Summary (Active Monitor)
    if 'df' in st.session_state:
        st.subheader("📊 Data Status")
        n_rows, n_cols = st.session_state.df.shape
        st.write(f"**Rows:** {n_rows:,}")
        st.write(f"**Columns:** {n_cols}")
        
        if 'target_col' in st.session_state:
            st.write(f"**Target:** `{st.session_state.target_col}`")
            
        if 'goal' in st.session_state:
            with st.expander("Target Goal"):
                st.write(st.session_state.goal)
    
    # 4. Context Help
    st.markdown("---")
    with st.expander("💡 Tip / Help", expanded=True):
        if st.session_state.step == 'upload':
            st.info("CSV 파일을 업로드하고 분석 목표를 설정하세요. AI가 자동으로 최적의 타겟을 찾습니다.")
        elif st.session_state.step == 'plan_edit':
            st.info("AI가 제안한 전처리 계획을 검토하세요. 필요하다면 액션을 직접 수정할 수 있습니다.")
        elif st.session_state.step == 'execute_loop':
            st.info("단계별로 데이터 변화를 확인하며 진행하세요. 'Apply'를 누르면 저장됩니다.")
        elif st.session_state.step == 'final':
            st.info("전처리가 완료된 데이터를 다운로드하거나 코드를 생성하세요.")

    st.caption("v1.3 - Enhanced Sidebar")
if st.session_state.step == 'upload':
    st.subheader("1. 데이터 & 목표 설정")
    uploaded_files = st.file_uploader(
        "데이터 파일을 업로드하세요 (CSV, Excel, JSON, Parquet supported)", 
        type=['csv', 'xlsx', 'xls', 'json', 'parquet'],
        accept_multiple_files=True
    )
    
    temp_df = None
    dataset_name = ""

    if uploaded_files:
        # 1. 파일 로딩
        loaded_dfs = {}
        for f in uploaded_files:
            try:
                if f.name.endswith('.csv'):
                    loaded_dfs[f.name] = pd.read_csv(f)
                elif f.name.endswith(('.xlsx', '.xls')):
                    loaded_dfs[f.name] = pd.read_excel(f)
                elif f.name.endswith('.json'):
                    loaded_dfs[f.name] = pd.read_json(f)
                elif f.name.endswith('.parquet'):
                    loaded_dfs[f.name] = pd.read_parquet(f)
            except Exception as e:
                st.error(f"❌ '{f.name}' 로드 실패: {e}")

        # 2. 병합 로직 (파일이 여러 개일 경우)
        if len(loaded_dfs) > 1:
            st.info(f"📂 {len(loaded_dfs)}개의 파일이 감지되었습니다. 병합 방식을 선택하세요.")
            
            with st.expander("🧩 데이터 병합 설정 (Data Merger)", expanded=True):
                merge_type = st.radio("병합 방식", ["Vertical (Concat) - 위아래로 합치기", "Horizontal (Merge) - 옆으로 합치기 (Key 기준)"])
                
                if "Vertical" in merge_type:
                    st.caption("모든 파일의 컬럼을 기준으로 위아래로 합칩니다. (컬럼명이 같아야 함)")
                    if st.button("Vertical Concat 실행"):
                        try:
                            temp_df = pd.concat(loaded_dfs.values(), axis=0, ignore_index=True)
                            dataset_name = f"Merged_{len(loaded_dfs)}_Files_Concat"
                            st.success(f"✅ 병합 완료! 총 {len(temp_df)}행")
                        except Exception as e:
                            st.error(f"병합 실패: {e}")
                else:
                    st.caption("두 개의 파일을 공통 컬럼(Key) 기준으로 합칩니다. (현재는 2개 파일 병합만 지원)")
                    file_names = list(loaded_dfs.keys())
                    c1, c2 = st.columns(2)
                    left_name = c1.selectbox("Left Data", file_names)
                    right_name = c2.selectbox("Right Data", [n for n in file_names if n != left_name])
                    
                    left_df = loaded_dfs[left_name]
                    right_df = loaded_dfs[right_name]
                    
                    # 공통 컬럼 찾기
                    common_cols = list(set(left_df.columns) & set(right_df.columns))
                    key_col = st.selectbox("Key Column (Join Key)", common_cols if common_cols else left_df.columns)
                    
                    if st.button("Horizontal Merge 실행"):
                        try:
                            temp_df = pd.merge(left_df, right_df, on=key_col, how='inner')
                            dataset_name = f"Merged_{left_name}_{right_name}"
                            st.success(f"✅ 병합 완료! 총 {len(temp_df)}행 (Inner Join on {key_col})")
                        except Exception as e:
                            st.error(f"병합 실패: {e}")

        # 3. 단일 파일인 경우
        elif len(loaded_dfs) == 1:
            name = list(loaded_dfs.keys())[0]
            temp_df = loaded_dfs[name]
            dataset_name = name

    if temp_df is not None:
        # AI Cache Logic Update (Use dataset_name instead of uploaded_file.name)
        # ⚠️ Large Data Handling (Smart Sampling)

        if len(temp_df) > 10000:
            st.warning(f"⚠️ 데이터가 꽤 큽니다 ({len(temp_df):,} Rows).")
            use_sample = st.checkbox("🚀 빠른 처리를 위해 10% 샘플링 사용 (권장)", value=True)
            if use_sample:
                temp_df = temp_df.sample(frac=0.1, random_state=42)
                st.success(f"✅ 샘플링 적용됨: {len(temp_df):,} Rows로 진행합니다.")
        
        # --- [Advanced EDA Tabs] ---
        st.markdown("### 🔍 Advanced Data Analysis (EDA)")
        tab1, tab2, tab3, tab4, tab5 = st.tabs(["📄 Data Preview", "📊 Distribution", "📉 Missing Values", "🔥 Correlation", "📦 Outliers"])
        
        with tab1:
            st.dataframe(temp_df.head(5))
            st.caption(f"Total Shape: {temp_df.shape}")

        with tab2:
            st.subheader("Numeric Distribution")
            numeric_cols = temp_df.select_dtypes(include=[np.number]).columns
            if len(numeric_cols) > 0:
                selected_dist_col = st.selectbox("Select Column to Visualize", numeric_cols, key="dist_col")
                fig_dist = px.histogram(temp_df, x=selected_dist_col, marginal="box", title=f"Distribution of {selected_dist_col}")
                st.plotly_chart(fig_dist, use_container_width=True)
            else:
                st.info("No numeric columns found.")

        with tab3:
            st.subheader("Missing Values Analysis")
            missing = temp_df.isnull().sum()
            missing = missing[missing > 0]
            if not missing.empty:
                fig_miss = px.bar(x=missing.index, y=missing.values, labels={'x': 'Column', 'y': 'Missing Count'}, title="Missing Values per Column")
                st.plotly_chart(fig_miss, use_container_width=True)
            else:
                st.success("✨ 결측치가 없는 데이터입니다! (No missing values)")

        with tab4:
            st.subheader("Correlation Heatmap")
            numeric_df = temp_df.select_dtypes(include=[np.number])
            if numeric_df.shape[1] > 1:
                try:
                    corr = numeric_df.corr()
                    fig_corr = px.imshow(corr, text_auto=True, color_continuous_scale='RdBu_r', aspect='auto')
                    st.plotly_chart(fig_corr, use_container_width=True)
                except:
                    st.warning("상관관계 계산 중 오류 발생")
            else:
                st.info("수치형 컬럼이 2개 이상 필요합니다.")

        with tab5:
            st.subheader("Outlier Detection (Box Plot)")
            if len(numeric_cols) > 0:
                selected_box_col = st.selectbox("Select Column for Box Plot", numeric_cols, key="box_col")
                fig_box = px.box(temp_df, y=selected_box_col, title=f"Box Plot of {selected_box_col}")
                st.plotly_chart(fig_box, use_container_width=True)
            else:
                st.info("No numeric columns.")
        
        if 'last_uploaded_file' not in st.session_state or st.session_state.last_uploaded_file != dataset_name:
            st.session_state.last_uploaded_file = dataset_name
            st.session_state.ai_goals = [] # Reset goals
            
            with st.spinner("AI가 데이터를 분석하여 적절한 분석 목표를 찾고 있습니다... 🕵️‍♀️"):
                st.session_state.ai_goals = suggest_goals(temp_df)
        
        st.markdown("---")
        st.subheader("🎯 분석 목표 설정")
        
        col_mode, col_goal = st.columns([1, 2])
        
        with col_mode:
            analysis_mode = st.radio(
                "분석 모드 선택",
                ["머신러닝 학습용 전처리", "일반 데이터 분석(EDA)"],
                captions=["모델 학습을 위한 Feature Engineering", "데이터 인사이트 도출 및 시각화"]
            )
        
        with col_goal:
            # 추천 목표 제안 (Pills)
            st.write(f"💡 AI 맞춤 추천 ({dataset_name}):")
            
            # AI가 제안한 목표가 있으면 그것을 사용, 없으면 기본값
            example_goals = st.session_state.get('ai_goals', ["데이터 탐색 (EDA)", "예측 분석"])
            
            # Session State를 이용해 텍스트 입력값 제어
            if "user_goal_input" not in st.session_state:
                st.session_state.user_goal_input = ""
            
            # 2x2 그리드로 배치
            cols_ex = st.columns(2)
            for idx, ex in enumerate(example_goals):
                if cols_ex[idx % 2].button(ex, key=f"ex_btn_{idx}", use_container_width=True):
                    st.session_state.user_goal_input = ex
            
            user_goal = st.text_input(
                "목표를 직접 입력하거나 위 AI 추천 버튼을 클릭하세요.", 
                value=st.session_state.user_goal_input, 
                placeholder="예: 이 데이터로 할 수 있는 가장 흥미로운 분석은?"
            )

        # 목표가 입력되면 타겟 추천 실행
        if user_goal:
            # 목표나 파일이 바뀌었을 때만 재실행
            current_context = f"{dataset_name}_{user_goal}"
            if 'last_context' not in st.session_state or st.session_state.last_context != current_context:
                st.session_state.last_context = current_context
                
                with st.spinner("목표에 맞춰 가장 적절한 타겟 변수를 찾는 중..."):
                    suggested = suggest_target_column(temp_df, user_goal)
                    st.session_state.suggested_target = suggested
                    st.toast(f"AI 추천: '{suggested}' 컬럼을 타겟으로 설정합니다.", icon="🎯")
            
            # 타겟 컬럼 선택 UI
            col_list = list(temp_df.columns)
            default_idx = 0
            if 'suggested_target' in st.session_state and st.session_state.suggested_target in col_list:
                default_idx = col_list.index(st.session_state.suggested_target)
                
            target_col = st.selectbox(
                "🎯 타겟 컬럼(정답지) 확인 및 변경", 
                col_list, 
                index=default_idx,
                help="모델이 예측해야 할 최종 목표 변수입니다."
            )
            
            st.markdown("---")
            if st.button("AI에게 계획 요청하기 🚀", type="primary", disabled=(not user_goal)):
                # 사용자가 최종 선택한 목표 저장
                st.session_state.goal = user_goal
                st.session_state.target_col = target_col
                
                with st.spinner("AI가 데이터를 분석하여 전처리 계획을 수립하고 있습니다... 🧠"):
                    # Pass the selected analysis mode
                    plan = get_agent_plan(temp_df, user_goal, target_col, mode=analysis_mode)
                    st.session_state.plan = plan
                    st.session_state.df = temp_df # 초기 데이터 저장
                    st.session_state.step = 'plan_edit'
                    st.rerun()

# [Step 2] 계획 검토 및 수정 (Plan Editor)
elif st.session_state.step == 'plan_edit':
    st.subheader("2. AI 제안 전처리 계획 검토")
    st.info("AI가 제안한 계획입니다. 마음에 들지 않으면 수정할 수 있습니다.")
    
    # 딕셔너리 리스트 -> DataFrame 변환
    plan_df = pd.DataFrame(st.session_state.plan)
    
    # 수정 가능한 Data Editor
    edited_plan_df = st.data_editor(
        plan_df,
        column_config={
            "col": st.column_config.TextColumn("컬럼명", disabled=True),
            "action": st.column_config.SelectboxColumn(
                "액션",
                options=["Pass", "Drop", "Fill_Median", "Fill_Mode", "Fill_Zero", "Normalize", "Encode_Label", "Encode_OneHot"],
                required=True
            ),
            "reason": st.column_config.TextColumn("이유 (AI 생성)", disabled=True)
        },
        use_container_width=True,
        hide_index=True,
        num_rows="fixed"
    )
    
    col1, col2 = st.columns(2)
    if col1.button("이대로 실행하기 ▶️", type="primary"):
        # 수정된 내용을 다시 리스트로 변환
        st.session_state.plan = edited_plan_df.to_dict('records')
        st.session_state.history = []  # Initialize history tracking
        st.session_state.step = 'execute_loop'
        st.rerun()
        
    if col2.button("처음으로 돌아가기"):
        st.session_state.step = 'upload'
        st.rerun()

# [Step 3] 실행 루프
elif st.session_state.step == 'execute_loop':
    # --- [New Feature] Custom Code Execution ---
    with st.expander("🛠️ Advanced: Execute Custom Python Code"):
        st.caption("현재 데이터프레임(`df`)에 직접 파이썬 코드를 적용할 수 있습니다. 예: `df['new'] = df['a'] + df['b']`")
        custom_code = st.text_area("Python Code", height=100)
        if st.button("Run Custom Code"):
            try:
                local_scope = {'df': st.session_state.df, 'pd': pd, 'np': np}
                exec(custom_code, globals(), local_scope)
                st.session_state.df = local_scope['df']
                st.success("Custom code executed successfully!")
                st.session_state.log.append("User executed custom code.")
                st.rerun()
            except Exception as e:
                st.error(f"Error: {e}")

    plan = st.session_state.plan
    idx = st.session_state.current_step_idx
    
    if idx < len(plan):
        current_item = plan[idx]
        col = current_item['col']
        action = current_item['action']
        reason = current_item['reason']
        
        # 이미 처리 과정에서 컬럼이 사라졌을 수도 있음 (예: 이전 단계의 OneHot 등)
        # 하지만 원본 컬럼명 기준 루프이므로, 현재 df에 col이 있는지 체크 필요
        col_exists = col in st.session_state.df.columns
        
        progress = (idx / len(plan))
        st.progress(progress, text=f"Processing... ({int(progress*100)}%)")
        
        st.subheader(f"Step {idx+1}/{len(plan)}: {col}")
        
        if not col_exists:
            st.warning(f"⚠️ 컬럼 '{col}'을(를) 찾을 수 없습니다. (이미 삭제되었거나 변형됨)")
            # 자동 스킵
            if st.button("다음으로 넘어가기"):
                st.session_state.log.append(f"Step {idx+1}: {col} -> Skipped (Not Found)")
                st.session_state.current_step_idx += 1
                st.rerun()
            st.stop()

        with st.chat_message("assistant", avatar="🤖"):
            st.markdown(f"**{col}** → **`{action}`**")
            st.caption(f"Reason: {reason}")

        # Preview
        preview_df = apply_step(st.session_state.df, col, action)
        
        with st.expander("🔍 결과 미리보기 (Interactive Chart)", expanded=True):
            if action != "Drop":
                plot_comparison(st.session_state.df, preview_df, col)
            else:
                st.error(f"🗑️ '{col}' 컬럼이 제거됩니다.")

        st.write("---")
        c1, c2, c3 = st.columns(3)
        if c1.button("✅ 승인 (Apply)", type="primary", use_container_width=True):
            st.session_state.history.append(st.session_state.df.copy())
            st.session_state.df = preview_df
            st.session_state.log.append(f"{col}: {action}")
            st.session_state.current_step_idx += 1
            st.rerun()
            
        if c2.button("❌ 건너뛰기 (Pass)", use_container_width=True):
            st.session_state.history.append(st.session_state.df.copy())
            # df 변경 없음
            st.session_state.log.append(f"{col}: Pass (User Skipped)")
            st.session_state.current_step_idx += 1
            st.rerun()
            
        if c3.button("↩️ 실행 취소 (Undo)", use_container_width=True):
            if st.session_state.history:
                st.session_state.df = st.session_state.history.pop()
                if st.session_state.log: st.session_state.log.pop()
                st.session_state.current_step_idx -= 1
                st.rerun()
            else:
                st.warning("돌아갈 단계가 없습니다.")

        st.markdown("---")
        if st.button("⏩ 남은 단계 일괄 승인 (Apply All Remaining)", type="secondary", use_container_width=True):
            with st.spinner("남은 모든 단계를 처리 중입니다..."):
                # 현재 단계부터 끝까지 루프
                current_plan = st.session_state.plan
                start_idx = st.session_state.current_step_idx
                
                # Undo를 위한 스냅샷 저장 (한 번만 저장하여 전체 취소 가능하게 하거나, 단계별로 하거나. 간단히 여기선 마지막 상태로 점프)
                # 복잡하므로 history에 현재 상태 하나는 저장해두자
                st.session_state.history.append(st.session_state.df.copy())

                for i in range(start_idx, len(current_plan)):
                    item = current_plan[i]
                    p_col = item['col']
                    p_act = item['action']
                    
                    # 실행
                    st.session_state.df = apply_step(st.session_state.df, p_col, p_act)
                    st.session_state.log.append(f"{p_col}: {p_act} (Batch Applied)")
                
                # 끝으로 이동
                st.session_state.current_step_idx = len(current_plan)
                st.rerun()

    else:
        st.session_state.step = 'final'
        st.rerun()

# [Step 4] 완료 및 다운로드
elif st.session_state.step == 'final':
    st.balloons()
    st.success("🎉 모든 전처리가 완료되었습니다!")
    
    final_df = st.session_state.df
    target_col = st.session_state.target_col
    
    st.subheader("📊 최종 데이터 요약")
    st.dataframe(final_df.head())
    st.write(f"Shape: {final_df.shape}")
    
    with st.expander("�️ 처리 로그"):
        for l in st.session_state.log:
            st.text(l)
            
    # --- Report Generator ---
    st.subheader("0. 📊 리포트 생성 (Report)")
    if st.button("Generate HTML Report 📄"):
        report_html = generate_html_report(
            df_info=str(final_df.shape),
            goal=st.session_state.get('goal', 'N/A'),
            target=target_col,
            plan=st.session_state.plan,
            logs=st.session_state.log,
            metrics="AutoML not run yet."
        )
        st.download_button("💾 Download Report (.html)", report_html, "report.html", mime="text/html")
        
    st.markdown("---")
    
    # --- Code Generator ---
    st.subheader("1. 📜 파이썬 코드 생성 (Code Generator)")
    
    script_type = st.radio("Script Engine", ["Pandas (Standard)", "Dask (Big Data > 10GB)"], horizontal=True)
    
    if st.button("Generate Python Code 🐍"):
        if "Dask" in script_type:
            st.session_state.gen_code = generate_dask_code(st.session_state.plan, target_col)
            st.session_state.gen_filename = "preprocessing_dask.py"
        else:
            st.session_state.gen_code = generate_python_code(st.session_state.plan, target_col)
            st.session_state.gen_filename = "preprocessing_pandas.py"
            
    if st.session_state.get("gen_code"):
        st.code(st.session_state.gen_code, language='python')
        st.download_button("💾 Download .py", st.session_state.gen_code, st.session_state.gen_filename)

    # --- AutoML ---
    st.markdown("---")
    st.subheader("2. 🤖 AutoML Baseline")
    if st.button("Run AutoML Training 🚀"):
        try:
             # Data Prep (Simplified - Reuse logic)
             if target_col in final_df.columns:
                 y_tmp = final_df[target_col]
                 X_tmp = final_df.drop(columns=[target_col])
             else:
                 target_cols = [c for c in final_df.columns if str(c).startswith(f"{target_col}_")]
                 if target_cols:
                     y_tmp = final_df[target_cols]
                     X_tmp = final_df.drop(columns=target_cols)
                 else:
                     st.error("Target missing.")
                     X_tmp = final_df
                     y_tmp = np.empty(len(final_df))

             # Numeric Cleaning
             X_tmp = X_tmp.apply(pd.to_numeric, errors='coerce').fillna(0)
             X_tmp = X_tmp.select_dtypes(include=[np.number])

             # Y Cleaning & Task Inference
             if isinstance(y_tmp, pd.DataFrame):
                 y_tmp = y_tmp.apply(pd.to_numeric, errors='coerce').fillna(0).values
                 if y_tmp.shape[1] > 1: y_tmp = np.argmax(y_tmp, axis=1)
             else:
                 y_tmp = pd.to_numeric(y_tmp, errors='coerce').fillna(0).values
             
             unique_y = len(np.unique(y_tmp))
             # Heuristic: < 20 classes or non-float => Classification
             is_clf = unique_y < 20 or (not np.issubdtype(y_tmp.dtype, np.floating))

             # Imports
             from sklearn.model_selection import train_test_split
             from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor, GradientBoostingClassifier, GradientBoostingRegressor
             from sklearn.linear_model import LogisticRegression, Ridge
             from sklearn.metrics import accuracy_score, r2_score, f1_score, mean_absolute_error
             import time
             
             X_tr, X_te, y_tr, y_te = train_test_split(X_tmp, y_tmp, test_size=0.2, random_state=42)
             
             models = []
             if is_clf:
                 task_name = "Classification"
                 metric_name = "Accuracy"
                 models = [
                     ("Logistic Regression", LogisticRegression(max_iter=500)),
                     ("Random Forest", RandomForestClassifier(n_estimators=50, random_state=42)),
                     ("Gradient Boosting", GradientBoostingClassifier(n_estimators=50, random_state=42))
                 ]
             else:
                 task_name = "Regression"
                 metric_name = "R2 Score"
                 models = [
                     ("Ridge Regression", Ridge()),
                     ("Random Forest", RandomForestRegressor(n_estimators=50, random_state=42)),
                     ("Gradient Boosting", GradientBoostingRegressor(n_estimators=50, random_state=42))
                 ]
             
             st.write(f"### 🏁 AutoML Race ({task_name})")
             results = []
             best_model = None
             best_score = -9999
             best_model_name = ""

             progress_bar = st.progress(0)
             
             for i, (name, model) in enumerate(models):
                 start_t = time.time()
                 model.fit(X_tr, y_tr)
                 train_time = time.time() - start_t
                 
                 score = model.score(X_te, y_te) 
                 # For additional metrics if needed
                 # if is_clf: extra = f1_score(y_te, model.predict(X_te), average='weighted')
                 
                 results.append({
                     "Model": name, 
                     metric_name: round(score, 4), 
                     "Time (s)": round(train_time, 3)
                 })
                 
                 if score > best_score:
                     best_score = score
                     best_model = model
                     best_model_name = name
                     
                 progress_bar.progress((i + 1) / len(models))

             # Leaderboard
             res_df = pd.DataFrame(results).sort_values(by=metric_name, ascending=False)
             st.success(f"🏆 Winner: **{best_model_name}** ({metric_name}: {best_score:.4f})")
             
             c1, c2 = st.columns([2, 1])
             with c1:
                 st.dataframe(res_df, use_container_width=True, hide_index=True)
             with c2:
                 st.plotly_chart(px.bar(res_df, x='Model', y=metric_name, color='Model', title="Score Comparison"), use_container_width=True)
             
             # Feature Importance
             if hasattr(best_model, 'feature_importances_'):
                 st.markdown("#### 🌟 Feature Importance")
                 fi = best_model.feature_importances_
                 fi_df = pd.DataFrame({'Feature': X_tmp.columns, 'Importance': fi}).sort_values(by='Importance', ascending=False).head(10)
                 fig_fi = px.bar(fi_df, x='Importance', y='Feature', orientation='h', title=f"Top 10 Features ({best_model_name})")
                 fig_fi.update_layout(yaxis={'categoryorder':'total ascending'})
                 st.plotly_chart(fig_fi, use_container_width=True)
             
        except Exception as e:
            st.error(f"AutoML Failed: {e}")

    # --- Tensor Gen ---
    st.markdown("---")
    st.subheader("3. 🧠 PyTorch Tensor 생성")
    # Tensor 생성 및 다운로드
    if st.button("Generate PyTorch Tensors"):
        # 1. Target 분리 attempt
        if target_col in final_df.columns:
            # 타겟이 변형되지 않았거나 LabelEncoding된 상태
            y = final_df[target_col]
            X = final_df.drop(columns=[target_col])
        else:
            # 타겟 컬럼이 OneHot 등으로 이름이 바뀌었거나 사라졌을 수 있음
            st.warning(f"타겟 컬럼 '{target_col}'이(가) 보이지 않습니다. One-Hot Encoding 되었을 수 있습니다.")
            # 이름에 target_col이 포함된 컬럼들을 y로 간주 (간이 로직)
            target_cols = [c for c in final_df.columns if str(c).startswith(f"{target_col}_")]
            if target_cols:
                y = final_df[target_cols]
                X = final_df.drop(columns=target_cols)
                st.info(f"타겟으로 추정되는 컬럼들: {target_cols}")
            else:
                st.error("타겟 컬럼을 찾을 수 없어 전체를 X로 사용합니다.")
                X = final_df
                y = pd.Series(np.zeros(len(X))) # Dummy y

        # 2. 데이터 타입 정리 (Data Type Cleaning)
        try:
            # X 처리: bool -> int, object -> numeric (coerce)
            # 1) Bool 타입 처리
            bool_cols = X.select_dtypes(include=['bool']).columns
            if len(bool_cols) > 0:
                X[bool_cols] = X[bool_cols].astype(int)
            
            # 2) Object 타입 강제 변환
            X = X.apply(pd.to_numeric, errors='coerce').fillna(0)
            
            # 3) 여전히 숫자가 아닌 컬럼 제거 (안전장치)
            non_numeric_cols = X.select_dtypes(exclude=[np.number]).columns
            if len(non_numeric_cols) > 0:
                st.warning(f"⚠️ 텐서 변환 불가 컬럼 제거됨 (Text/Object): {list(non_numeric_cols)}")
                X = X.drop(columns=non_numeric_cols)

            # y 처리
            if isinstance(y, pd.DataFrame):
                bool_cols_y = y.select_dtypes(include=['bool']).columns
                if len(bool_cols_y) > 0:
                    y[bool_cols_y] = y[bool_cols_y].astype(int)
                y = y.apply(pd.to_numeric, errors='coerce').fillna(0).values
            else:
                y = pd.to_numeric(y, errors='coerce').fillna(0).values
            
            # 최종 Numpy 변환 (float32)
            X_values = X.values.astype(np.float32)
            y_values = y.astype(np.float32)

            X_train, X_test, y_train, y_test = train_test_split(X_values, y_values, test_size=0.2, random_state=42)
            
            device = "cuda" if torch.cuda.is_available() else "cpu"
            
            X_train_t = torch.tensor(X_train, dtype=torch.float32).to(device)
            X_test_t = torch.tensor(X_test, dtype=torch.float32).to(device)
            y_train_t = torch.tensor(y_train, dtype=torch.float32).to(device)
            y_test_t = torch.tensor(y_test, dtype=torch.float32).to(device)
            
            st.write(f"Device: {device}")
            st.code(f"X_train: {X_train_t.shape}\ny_train: {y_train_t.shape}")
            
            # Save
            buffer = io.BytesIO()
            torch.save({
                'X_train': X_train_t, 'X_test': X_test_t,
                'y_train': y_train_t, 'y_test': y_test_t,
                'feature_names': list(X.columns)
            }, buffer)
            
            st.download_button("💾 Download .pt file", buffer.getvalue(), "data.pt")
            
        except Exception as e:
            st.error(f"텐서 변환 중 치명적 오류 발생: {e}")
            st.write("힌트: 데이터에 텍스트가 남아있거나, 메모리 부족일 수 있습니다.")